### ISSUE TITLE
jft assistant automatic installer

### ISSUE THREAD

**Issue by selul** [Codeinwp/jft-assistant#15] opened 2018-01-15 14:16 UTC
@contactashish13 I would like we to work on an automatic theme installer for the assistant. 

The intent is when someone chooses to download with JFT assistant a theme after he will install the JFT assistant plugin, he will get automatically installed and activated that theme. 

The problem that we will try to fix is that when a user downloads the jft-assitant plugin, he will need to search again that theme he saw previously and choose to install and activate. Using this feature, he will see in the dashboard after plugin install, a popup like,  `Do you want to install and activate Hestia`, assuming that Hestia was the theme he was interested. That popup will be inside the wp-admin dashboard, on the JFT listing page. 

More details on this: 

* When someone chooses to download the theme with JFT assistant, set up a cookie on the JFT domain, having as value the theme id. 
* After he installs and activate the JFT plugin, redirect to listing page and do an ajax call to jft.com which will return the cookie value ( if exists ) 
* If the cookie exists, show a popup like ( Would you like to proceed with the install and activate of Hestia theme ). 
* If positive, we will download/install/activate the theme.

Let me know if you have any q.

**Comment by contactashish13** [comment] 2018-01-21 05:38
PRs: https://github.com/Codeinwp/justfreethemes/pull/79 and https://github.com/Codeinwp/jft-assistant/pull/17

**Comment by selul** [comment] 2018-02-15 08:11
@contactashish13 i'm not sure what's the deal with jft-chosen string -> https://github.com/contactashish13/jft-assistant/commit/9a17d6f4dc11fe31d723f73ef3834d2aec3a4370#diff-559e36b702a3c723116bca3d4ec6fd5aR11 

Can you tell me what the purpose of this ?

**Comment by contactashish13** [comment] 2018-02-21 02:19
@selul Please check the comment here: https://github.com/contactashish13/jft-assistant/blob/9a17d6f4dc11fe31d723f73ef3834d2aec3a4370/classes/JftAssistant/Admin.php#L228

**Comment by selul** [comment] 2018-02-21 09:58
@contactashish13 im not sure why do you need to save the theme name, i.e `jft-chosen`, the intent is to work for any theme that user downloaded from JFT.

**Comment by contactashish13** [comment] 2018-02-21 10:41
@selul if you test this you will see it works for any theme. Let me know if you feel its not working

**Comment by selul** [comment] 2018-02-21 10:45
yep, but i wanted to know the intent of using that constant.

**Comment by contactashish13** [comment] 2018-02-21 10:47
I think it was because the name of theme is not sent and I need to use a hardcoded constant so that I can determine this request is for the automatic installer and get the theme name from the cookie. There was no other way this was working but if you feel it could be improved, let me know and I'll test it out

**Comment by selul** [comment] 2018-02-21 13:41
@contactashish13 can you tell me how can i test it ? A video where you can outline how this worked is very much appreciated.

**Comment by contactashish13** [comment] 2018-02-23 10:53
@selul I can't show you a video because enabling live link in local by flywheel is a hit-and-miss and requests timeout more often than not with `502 Bad Gateway`. So testing is really arduous. But here are some snapshots:

1. download the theme and click on download with jft assistant. The cookie is created.
![image](https://user-images.githubusercontent.com/12953439/36590332-53c06872-18b4-11e8-9842-3492760844d1.png)

2. When you install and activate JFT assistant for the first time, it will search for a cookie and get the name and ID of the theme. The cookie is immediately deleted.
![image](https://user-images.githubusercontent.com/12953439/36590405-93a5f358-18b4-11e8-9346-d582f9f47164.png)

3. The name is used to display the alert and the ID is used to get the details of the theme from the endpoint.

If you can set up a JFT testing instance so that I don't have to use local by flywheel, it will greatly help.

**Comment by selul** [comment] 2018-02-26 08:59
@contactashish13 

1. Can't we use two local instances, build with Local by Flywheel ? One will have the jft blueprint and one will have the installer. You can publish the jft instance and test the theme installer.
2. There are a lot of constants which are using the same base url -> http://prntscr.com/ijtxar, can't we use a single one for root url, and use the proper sufix based on the context.
3. Please no longer use the __ termination for the constants, imho it makes the code looks ugly, for the moment we can keep it like this but in the future, please no longer use it.

**Comment by contactashish13** [comment] 2018-02-27 04:56
@selul I'm not sure I understand the intent behind all this. I have tested the code and it works. I'm not sure if you have tested it yet. Local by flywheel on a dev instance does not work well with re-entrant calls. It takes a **huge** amount of time as well causing timeouts galore. I'm simply asking for an easier mechanism so that you can test and I can also reproduce bugs. The easiest mechanism I have in mind is a duplicate of the JFT site where we can test this kind of functionality. Having 2 instances of local by flywheel will not work any better because it is finally calling a public URL that comes back into my dev server.

**Comment by selul** [comment] 2018-02-27 07:18
Oh, @contactashish13, you're killing me 🙉 I will try to test this and get back to you. 
How about 2,3 does the intent seems reasonable to you? 
Thanks!

**Comment by contactashish13** [comment] 2018-02-28 05:50
@selul PR: https://github.com/Codeinwp/jft-assistant/pull/18

**Comment by selul** [comment] 2018-03-05 16:58
@contactashish13 as i suspected the automatic install feature was not working at all. You were checking the cookie using the server and not the user browser using ajax as i first suggested -> http://prntscr.com/in78g9 . 

If you are checking the cookie using the server-side code, the cookie will be null as the cookie is not set on the client server, it's on he's browser. 

Please check the changes that i've done, you can close the ticket after. 
I will try to spend more on the scenarios that we can use to test, in order to avoid such things in the future.

**Closed** 2018-03-07 08:38 UTC
Labels: enhancement
